export const IDs = {
  myBlackbird: 'myBlackbird',
  filters: 'bbFilters',
  controls: 'bbControls',
    // size: 'bbSize',
  sendEmail: 'sendEmail',
  copyLog: 'copyLog',
  slider: 'slider',
  buttonBar: 'buttonBar',
  log: 'myBlackbird',
  btnToggleLog: 'btnToggleLog',
  btnToggleSlider: 'btnToggleSlider',
  btnTogglePlayerSettings: 'btnTogglePlayerSettings',
  btnToggleAdSettings: 'btnToggleAdSettings',
  btnTogglePlaybackInfo: 'btnTogglePlaybackInfo',
  btnToggleDebuggerSettings: 'btnToggleDebuggerSettings',
  classesList: 'classesList',
  playerSettings: 'playerSettings',
  playbackInfo: 'playbackInfo',
  debuggerSettings: 'debuggerSettings',
  btnToggleClassList: 'btnToggleClassList',
    // bigPlayButtonStyles: 'bigPlayButtonStyles',
    // posterStyles: 'posterStyles',
  logTable: 'logTable',
  logList: 'logList',
  logJSON: 'logJSON',
  mediaSettings: 'mediaSettings',
  adSettings: 'adSettings'
};
